### ISSUE TITLE
Unknown name "charpath" in `pst-text`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#35] opened 2021-09-01 03:50 UTC
Package `pst-text` does not return errors except for `charpath`, but the output is wrong.

 ```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY -dPDFSETTINGS=/prepress ] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress} % only for the test examples, can later be empty
\documentclass[parskip=half-,DIV=13]{scrartcl}
\usepackage{pstricks}
\usepackage{pst-text}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
% from doc
\begin{pspicture}(-2,-2.5)(2,2.5)
\psset{linewidth=0.2pt}
  \pstextpath[c](0,0){\pscircle{2}}{\Large Now just text is written in a circle.}
\end{pspicture}

\DeclareFixedFont{\RM}{T1}{ptm}{b}{n}{2cm}
\pscharpath{\RM TeXnik}\par
\pscharpath[linecolor=lightgray]{\RM TeXnik}

\DeclareFixedFont{\SF}{T1}{phv}{b}{n}{2.45cm}
\begin{center}
\pstextpath(0,-1ex){\pscharpath*[linestyle=none]{\SF Herbert Vo\ss}}{
\scriptsize Du nimmst alles wahr, die Augen sind offen -
Doch Du verstehst nichts, du bist zu betroffen -
Die Angst bestimmt dein Handeln -
Es ist, als w\"urdest du dich verwandeln -
Ein anderer Mensch scheint es sehr -
Bist du nun und es geht gar nichts mehr -
Verzweifelt legst du dich nieder -
Doch der Frieden, er kommt nicht wieder -
Die Augen sind hellwach -
Es beginnt doch erst die Nacht -
Leicht d\"mmerst du in den Schlaf -
und kommst dir vor, wie in einem Grab -
Mit einem Mal bist du hellwach -
Es ist, als h\"ttest du dauernd gedacht, -
Nun verstehst du alles, wie es war \ldots
}
\end{center}

\DeclareFixedFont{\RM}{T1}{ptm}{b}{n}{3cm}
\begin{pspicture*}[showgrid=true](\linewidth,3cm)
  \begin{pscharclip}[linewidth=0.1pt]{%
    \rput(0.5\linewidth,1.5){\RM PSTricks}}%
  \end{pscharclip}
\end{pspicture*}

\begin{pspicture}[showgrid](10,10)
  \psCircleText[fontsize=6.5mm,radius=4cm](5,5){All is Fun with the typesetting system TeX}%
  \psCircleText[fillcolor=blue!40,fontsize=1cm,font=Helvetica](5,5){All is Fun within the World}%
\end{pspicture}

\begin{pspicture}(10,5)
  \psWarp[fillcolor=red!40,fontsize=0.5cm,font=Times-Roman]{All is Fun with the typesetting system LaTeX}%
  \psWarp[fillcolor=green,fontsize=12pt](0,2){What a wonderfull day, it is raining and I do not know what to do...}%
\end{pspicture}
\end{document}
```

```raw
xlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] [2./luapstricks.lua:5
38: Unknown name "charpath"
stack traceback:
	[C]: in function 'error'
	./luapstricks.lua:538: in upvalue 'lookup'
	./luapstricks.lua:2813: in upvalue 'execute_tok'
	./luapstricks.lua:2843: in upvalue 'execute_ps'
	./luapstricks.lua:2904: in function <./luapstricks.lua:2901>
	[C]: in function 'vf.node'
	./luapstricks.lua:2894: in function <./luapstricks.lua:2885>.
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

l.62 \end{document}
                 
? 
```

Expected output:

![test-crop-1](https://user-images.githubusercontent.com/2289461/131608778-7850fc1d-823d-42b1-b255-4ce57a99dfc6.png)
![test-crop-2](https://user-images.githubusercontent.com/2289461/131608776-2dc741b8-c1cf-4c54-b2fe-c83aef3141dc.png)

**Comment by hvoss49** [comment] 2021-09-06 17:16
> Package `pst-text` does not return errors except for `charpath`, but the output is wrong.

Marcel,
Is it possible to fix it? Then we can close some more packages.

**Comment by zauguin** [comment] 2021-09-06 19:06
> > Package `pst-text` does not return errors except for `charpath`, but the output is wrong.
> 
> Marcel,
> Is it possible to fix it? Then we can close some more packages.

Not in the short term. This involves writing a parser for CFF/Type 1 and TrueType fonts followed by integrating them into this. I think I have some semi functional Lua based parsers for most of these somewhere, but it's still quite some work.

**Comment by hvoss49** [comment] 2021-09-13 14:28
The `charpath` is more or less funny stuff but not really important. But what about writing text on a given curve:

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress} 
\documentclass{article}
\pagestyle{empty}
\usepackage{pst-text}
\begin{document}
\pstextpath[c](0,0){\pscircle{2}}{Now just text is written in a circle.}
\end{document}
```
this example runs without any error, but has no text on the circle path.
That should be much more easier to fix and is really useful.

**Comment by zauguin** [comment] 2021-09-14 12:35
> That should be much more easier to fix and is really useful.

I experimentally added a `.texboxforall` to iterate over the node in a hbox stored in a .TeXBox resource and a version of `pst-text.tex/pro` using this to implement `\pstextpath` for LuaLaTeX. It's *slow* though (Combining two relativly simple examples gave me  alightlymore then two minutes runtime).

The runtime is dominated by `/PathPosition`, more specifically `/@linetoproc`.

It might make sense to evaluate if it would be faster to provide an equivalent of `/PathPosition` as an operator implemented in Lua at a later point. Until the the only effective approach to make it faster seems to be to increase the flatness parameter with `setflat`.

One other issue: Instead of dropping all characters which do not fit onto the path, they are all written to coordinates `(0, 0)`. While I do see why this happens, I don't really understand why this doesn't happen with dvips, therefore I didn't manage to fix it.

**Comment by hvoss49** [comment] 2021-09-14 15:23
did you commit these chamges??

**Comment by hvoss49** [comment] 2021-09-14 16:53
Works fine, except that color commands are ignored. Not really important ...

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass[border=5mm]{standalone}
\usepackage{pst-3dplot,pst-text,dantelogo,hvlogos}
\begin{document}
\begin{pspicture}(-3.2,-1.55)(3.25,2.75)
  \pstThreeDCoor[zMax=3]
  \pstextpath{%
    \parametricplotThreeD[xPlotpoints=200,linestyle=none](0,2160){%
      2.5 t cos mul
      2.5 t sin mul
      t 450 div
    }
  }{\large\red
   \dantelogo\ \eV %
   \normalsize\textcolor{green}%
    {in Darmstadt im Jahre 2004 }%
    \blue bei einem Vortrag über %
    {\magenta\Huge \texttt{PSTricks}} und seine vielen Pakete (Herbert Vo\ss{} und Rolf Niepraschk.
  }%
\end{pspicture}
\end{document}
```

**Comment by zauguin** [comment] 2021-09-14 17:06
That's because nodes are surrounded by `gsave`/`grestore`. Probably can be fixed with
```diff
diff --git a/PSTricksFiles/pst-text.pro b/PSTricksFiles/pst-text.pro
index 7e7460c..0b26f1b 100644
--- a/PSTricksFiles/pst-text.pro
+++ b/PSTricksFiles/pst-text.pro
@@ -77,8 +77,8 @@ tx@TextPathDict begin
     /Voffset exch def
   grestore
   gsave
+  matrix currentmatrix exch
   { % The stack contains: mark [...] op x y dx dy id, where id is the type of the node, dx the advance width, dy is 0, (x, y) the offset and op an operator drawing the node to coordinates (0, 0)
-    gsave
     pop % Ignore the type of the Node
     2 div /Sy exch def
     2 div /Sx exch def
@@ -88,7 +88,7 @@ tx@TextPathDict begin
     Sx neg Sy neg translate
     currentdict exch end exec begin
     cleartomark % Should always come at the end because later versions might push additional entries.
-    grestore
+    dup setmatrix
   }
   .texboxforall
   grestore
```
Of course this has also means that adding unexpected nodes can have odd effects since they are less isolated.

**Comment by hvoss49** [comment] 2021-09-15 06:52
Is it possible to define a dummy function `charpath` which pops two arguments and leaves an empty path on the stack. Then
I can test a lot of examples from pst-solides3d. If I define on PS level:

`/charpath known not { /charpath { pop pop } def } if  % pops <string> and <true>`

I get an error from luapstricks that I do a pop on an empty stack.

**Comment by zauguin** [comment] 2021-09-15 14:28
> I get an error from luapstricks that I do a pop on an empty stack.

That wouldn't be different when it were implemented in Lua When building the documentation, this is caused by some odd interaction of the `\psProjection` in Chapter 2 and `\psSolid[object-courbe]` in `par-solidespredefinis-en.tex`: During `\psProjection`, `/function` gets defined in `SolidesDict`. Then later in `\psSolid[object-courbe]`, it again gets defined this time in outside of a `SolidesDict` block but used inside, so it gets hidden, causing the issue.

**Comment by hvoss49** [comment] 2021-09-15 16:04
sure, but  that depends to _some_ examples, but not for all.
With `systemdict /charpath known not { /charpath { pop pop } def } if` I can run other examples, which are not affected.

**Comment by zauguin** [comment] 2021-09-15 16:21
> sure, but that depends to _some_ examples, but not for all.
> With `systemdict /charpath known not { /charpath { pop pop } def } if` I can run other examples, which are not affected.

Sorry, I don't understand this comment. Especially:

> Is it possible to define a dummy function `charpath` which pops two arguments and leaves an empty path on the stack

Is there any case where such a dummy function would behave significantly different than your existing `/charpath known not { /charpath { pop pop } def } if`?

**Comment by hvoss49** [comment] 2021-09-15 16:25
No, there is no difference. Two days ago I thought that it should be in luapstricks. But now it is also fine in the pro-file which doesn't hurt.  Sorry for the noise ... 

And by the way: I am on vacation for the next 10 days with only limited internet access ...

**Closed as completed by hvoss49** 2021-09-15 16:25 UTC

**Comment by zauguin** [comment] 2021-09-15 16:44
> And by the way: I am on vacation for the next 10 days with only limited internet access ...

Enjoy your vacation! BTW I'm planning to send a first luapstricks version to CTAN in the next days (mostly to avoid weird error messages when people try to load pstricks in LuaLaTeX and the module isn't found...)

**Comment by hvoss49** [comment] 2021-09-15 17:02
Yes, publishing to CTAN makes sense ...
