### ISSUE TITLE
parse error with \psboxfill

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#42] opened 2021-09-02 16:18 UTC
```
)...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:125: Failed to par
se PS tokens at `{ end'
stack traceback:
	[C]: in function 'error'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:125: in upvalue 'p
arse_ps'
	...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:3065: in function 
<...ive/texmf-local/tex/generic/pstricks-lua/luapstricks.lua:3063>.
\pst@AutoBoxFill ...{\pst@dict /Box \pslbrace end}
                                                  \ifx \PstTiling \@undefine...

l.18 \end
       {pspicture}
```
Happens with all examples of package `pst-fill` and macro `\pst@AutoBoxFill`:

```
\def\pst@AutoBoxFill{%
  \leavevmode
  \begingroup
    \pst@stroke
    \pst@FlushCode
    \pst@Verb{\psk@boxfillangle\space \tx@RotBegin}%
    \pstVerb{\pst@dict /Box \pslbrace end}%
[...]

```
```
\documentclass[border=5mm]{standalone}
\usepackage[tiling]{pst-fill}
\newcommand\SheepHead[1]{%
  \begin{pspicture}(3,1.5)
    \pscustom[liftpen=2,fillstyle=solid,fillcolor=#1]{
      \pscurve(0.5,-0.2)(0.6,0.5)(0.2,1.3)(0,1.5)(0,1.5)(0.4,1.3)(0.8,1.5)(2.2,1.9)
        (3,1.5)(3,1.5)(3.2,1.3)(3.6,0.5)(3.4,-0.3)(3,0)(2.2,0.4)(0.5,-0.2)}
   \pscircle*(2.65,1.25){0.12\psunit} % Eye
   \psccurve*(3.5,0.3)(3.35,0.45)(3.5,0.6)(3.6,0.4)% Muzzle
   \pscurve(3,0.35)(3.3,0.1)(3.6,0.05)% Mouth
   \pscurve(2.3,1.3)(2.1,1.5)(2.15,1.7)\pscurve(2.1,1.7)(2.35,1.6)(2.45,1.4)
   \end{pspicture}}
\begin{document}
\psboxfill{\pspicture(0.25,0.25)\psframe[linecolor=black!15](0.25,0.25)\endpspicture}
\psboxfill{\psset{unit=0.5}\SheepHead{yellow}\SheepHead{cyan}}
\begin{pspicture}(10,5)
  \psframe[fillstyle=boxfill,fillcyclex=2,fillloopadd=1](10,5)
\end{pspicture}
\end{document}
```

expected output:

<img width="441" alt="Bildschirmfoto 2021-09-02 um 18 18 03" src="https://user-images.githubusercontent.com/12891199/131880355-69f987db-2ef4-4514-9762-314603c46c8c.png">

**Comment by zauguin** [comment] 2021-09-02 16:43
I don't think there is much hope to really fix this. It is an attempt to capture the PostScript instructions to draw TeX content into a PostScript procedure. Since in LuaLaTeX most content is never expressed in PostScript, that doesn't really work out.

Maybe an alternative implementation archiving the same overall effect could be implemented. If I understand the code correctly, it is basically drawing a TeX box register multiple times controlled by PS, right? Would it help if there was a PostScript command which allowed to draw an arbitrary TeX box?

By the way, how is this handled in XeTeX (well, xdvipdfmx)? I would expect that they encounter similar issues?!

**Comment by hvoss49** [comment] 2021-09-10 19:58
In `xetex` it is not possible, a "Box" error. However, it should be possible with `lualatex`

```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass[border=5mm]{standalone}
\usepackage[tiling]{pst-fill}
\usepackage{graphicx}
\begin{document}
\psboxfill{\includegraphics[scale=0.15]{rose}}

\begin{pspicture}(2.1,2.1)
  \psframe[fillstyle=boxfill,fillloopadd=1](2,2)
\end{pspicture}

\end{document}
```

`\psboxfill` creates a box on TeX level which is then placed in rows and columns into the area.

**Comment by zauguin** [comment] 2021-09-12 04:24
I added a new macro `\luaPSTbox` which reads a box command (it basically accepts everything which could be used after `\setbox0=`) and expands to a unspecified PostScript object which can be used as a key for a `.TeXBox` resource corresponding to an operator drawing the box. So the usage is e.g.

```latex
\documentclass{article}
\begin{document}
\begin{pspicture}(10,5)
  \pscircle{2}
  \pstverb{
    \fontid\font\space .findfontid
    10 scalefont
    setfont
    (Hello) show
    currentpoint translate
    \luaPSTbox\hbox{ World!} /.TeXBox 2 copy
    findresource /Box exch def
    undefineresource
    Box
  }
\end{pspicture}
\end{document}
```

I think that should allow such functionality to be implemented.

I tried to adapt `pst-fill.tex` with the following patch:

```diff
diff --git a/usr/local/texlive/2021/texmf-dist/tex/generic/pst-fill/pst-fill.tex b/./pst-fill.tex
index df7b945..d71d9c5 100644
--- a/usr/local/texlive/2021/texmf-dist/tex/generic/pst-fill/pst-fill.tex
+++ b/./pst-fill.tex
@@ -275,6 +275,11 @@ T moveto Box restore
   } def>
 
 \pst@def{BoxFill}<%
+  20 dict begin
+  \ifPSTlualatex
+    /save /gsave load def
+    /restore /grestore load def
+  \fi
   gsave
     gsave \tx@STV CM grestore dtransform CM idtransform
     abs /h ED abs /w ED
@@ -336,7 +341,7 @@ T moveto Box restore
           neg
 %%============
           \fi
-  T moveto Box restore
+  T moveto currentdict end Box begin restore
           /x x w add def
           0 hmove translate
           } repeat
@@ -344,9 +349,61 @@ T moveto Box restore
        /y1 y1 h add def
        wmove 0 translate
        } repeat
+  end
   currentpoint currentfont grestore setfont moveto>
 \fi
 
+\ifPSTlualatex
+\def\pst@AutoBoxFill{%
+  \leavevmode
+  \begingroup
+    \pst@stroke
+    \pst@FlushCode
+    \pst@Verb{\psk@boxfillangle\space \tx@RotBegin}%
+    % \pstVerb{[matrix currentmatrix aload stack cleartomark \pst@dict /Box [ \luaPSTbox\hbox{%
+    \pstVerb{\pst@dict /Box [ /gsave cvx /currentpoint cvx /translate cvx \luaPSTbox\hbox{%
+        \ifx\PstTiling\@undefined
+        \else
+          \ifx\pst@tempa\@undefined % Undefined for instance for \pscharpath
+          \else\ifx\pst@tempa\@empty\else
+            \def\pst@temph{0}%
+            \ifx\pst@tempa\pst@temph
+            \else
+              % \pstVerb{/TR {pop pop currentpoint translate \pst@tempa\space translate } def}%
+            \fi
+          \fi\fi
+        \fi
+        \hbox to \z@{\vbox to\z@{\vss\copy\pst@fillbox\vskip-\dp\pst@fillbox}\hss}%
+      } /.TeXBox findresource /grestore cvx ] cvx def
+      % } /.TeXBox findresource ] cvx def
+      \ifx\PstTiling\@undefined
+        \ifnum\psk@fillcycle=\z@
+          /s {} def
+        \else
+          \psk@fillcycle \tx@AutoFillCycle
+        \fi
+      \else
+        \ifnum\psk@fillcyclex=\z@
+          /CycleX {} def
+        \else
+          \psk@fillcyclex\space \tx@AutoFillCycleX
+        \fi
+        \ifnum\psk@fillcycley=\z@
+          /CycleY {} def
+        \else
+          \psk@fillcycley\space \tx@AutoFillCycleY
+        \fi
+      \fi
+      \pst@number{\wd\pst@fillbox}%
+      \psk@fillsepx\space add
+      \pst@number{\ht\pst@fillbox}%
+      \pst@number{\dp\pst@fillbox}%
+      \psk@fillsepy\space add add
+      \tx@BoxFill
+    end}%
+    \pst@Verb{\tx@RotEnd}%
+  \endgroup}
+\else
 \def\pst@AutoBoxFill{%
   \leavevmode
   \begingroup
@@ -404,6 +461,7 @@ T moveto Box restore
     \fi
     \pst@Verb{\tx@RotEnd}%
   \endgroup}
+\fi
 \catcode`\@=\PstAtCode\relax
 \endinput
 %%
```

Similar changes to the `BoxFill` one are needed at other places, but I already encountered an issue that my fillings seem to have some shift to the lower right and I don't understand the existing code enough to figure out what the problem is.

**Comment by hvoss49** [comment] 2021-09-12 19:32
looks good, except the coordinate system, which has wrong y direction. Will fix it later.
However, compare 0602...0615 at https://hvoss.org/PSTexa/index.html for better results

@zauguin: What you saw was the wrong \psrotateleft and \psrotateright, which must rotate the other way round for lualatex.

**Comment by hvoss49** [comment] 2021-09-28 10:12
I run into a problem with the following example, which works fine with `dvips`:

```
) [1{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}
! luapstricks: "rangecheck" error occured while executing PS code from "./test.tex:29".
<inserted text> BAD
   
l.32 \end{document}
```

Code:
```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage[tiling]{pst-fill}

\begin{document}

\newcommand\Square{\begin{pspicture}(1,1)\psframe[dimen=middle](1,1)\end{pspicture}}
\newcommand\Tiling[1]{%
 \begin{pspicture}#1
     \psframe[fillstyle=boxfill]#1
\end{pspicture}}

  \newcommand\ProtoTile{%
    \Square
    \pscustom{%
      \moveto(-0.9,0.75) % In PSTricks units
      \code{%
        /Times-Italic findfont 8 scalefont setfont
        (\string\() show row 3 string cvs show (,) show 
        column 3 string cvs show (\string\)) show}
      \moveto(-0.5,0.25) % In PSTricks units
      \code{%
        /Times-Bold findfont 18 scalefont setfont
        1 0 0 setrgbcolor % Red color
        /center {dup stringwidth pop 2 div neg 0 rmoveto} def
        row 1 sub x2 mul column add 3 string cvs center show}}}

  \psboxfill{\ProtoTile}
  \Tiling{(6,4)}

\end{document}
```

I also uploaded the modified `pst-fill.tex` into the PSTricks directory

**Comment by hvoss49** [comment] 2021-09-28 10:16
> I added a new macro `\luaPSTbox` which reads a box command (it basically accepts everything which could be used after `\setbox0=`) and expands to a unspecified PostScript object which can be used as a key for a `.TeXBox` resource corresponding to an operator drawing the box. So the usage is e.g.
 
 ```
 \pst@def{BoxFill}<%
 +  20 dict begin
 ```

I do not used a dictionary because row and columns are then not known.

**Comment by hvoss49** [comment] 2021-09-28 11:38
> I run into a problem with the following example, which works fine with `dvips`:

>       \code{%
>         /Times-Bold findfont 18 scalefont setfont
>         1 0 0 setrgbcolor % Red color
>         /center {dup stringwidth pop 2 div neg 0 rmoveto} def
>         row 1 sub x2 mul column add 3 string cvs center show}}}

it counts well until 6 but instead of 7 there is a floating number:
```

1
2
3
4
5
6
29.4527
```

**Comment by hvoss49** [comment] 2021-09-28 17:51
I solved it by using an own dictionary `fill@Dict` which is defined in `pstricks.pro`. Now the only problem are the coordinates, as usual :-)

<img width="274" alt="Bildschirmfoto 2021-09-28 um 19 48 34" src="https://user-images.githubusercontent.com/12891199/135139519-dc799946-85d6-4347-a43b-3973a4f8f0a0.png">

**Comment by hvoss49** [comment] 2021-09-28 18:42
I uploaded `pstricks.pro` and a slightly modified. `pst-fill.tex`. I cannot find the problem why pathbbox (l. 293) has completely different values for `lualatex`. My example:

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{article}
\usepackage[tiling]{pst-fill}

\begin{document}

\newcommand\Square{\begin{pspicture}(1,1)\psframe[dimen=middle](1,1)\end{pspicture}}
\newcommand\Tiling[1]{%
 \begin{pspicture}#1
     \psframe[fillstyle=boxfill]#1
\end{pspicture}}

  \newcommand\ProtoTile{%
    \Square
    \pscustom{%
      \moveto(-0.9,0.75) % In PSTricks units
      \code{%
        /Times-Italic findfont 8 scalefont setfont
        fill@Dict begin
        (\string\() show row 3 string cvs show (,) show 
        column 3 string cvs show (\string\)) show}
      \moveto(-0.5,0.25) % In PSTricks units
      \code{%
        /Times-Bold findfont 18 scalefont setfont
        1 0 0 setrgbcolor % Red color
        /center { dup stringwidth pop 2 div neg 0 rmoveto } def
        row 1 sub x2 mul column add 3 string cvs center 
        show
        end
      }}}

  \psboxfill{\ProtoTile}
  \Tiling{(6,4)}

\end{document}

```

**Comment by zauguin** [comment] 2021-09-29 01:19
The cause for the different values are different coordinate systems. The current matrix for luapstricks when entering pstVerb is `10 0 0 10 0 0` (which is the same as `defaultmatrix` in both gs and luapstricks), while with dvips the matrix is `1.2 0 0 -1.2 720 7200`.

Adding
```
    gsave matrix defaultmatrix setmatrix [ pathbbox stack cleartomark
```
to output the bounding box under the default matrix shows that the results would be the same if they were done in the same coordinate system.

I don't know why this leads to issues though. Since the same transformation is applied to everything, I would have expected these to cancel out. (At least the horizontal changes, vertical differences due to the flipped axis seem less surprising.

**Comment by hvoss49** [comment] 2021-09-29 11:16
I can correct the values manually, but have to do it for every image. For example in pst-fill.tex lines 330 ...333:

```
  \ifPSTlualatex
    /x1 x1 64 add  def
    /y1 y1 268 add  def
  \fi
```

then the output of `\Tiling{(12,12)}` looks fine:

<img width="541" alt="Bildschirmfoto 2021-09-29 um 13 09 08" src="https://user-images.githubusercontent.com/12891199/135257800-e40d3c15-b07d-444f-9c1a-2c94c10aa44e.png">

But as you can also see, if another example follows, here `\Tiling{(6,4)}` id fails, because the above value for y1 is wrong. I cannot figure out how I have to take the current point values into account for a correct setting. 

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{article}
\usepackage[tiling]{pst-fill}

\begin{document}

\newcommand\Square{\begin{pspicture}(1,1)\psframe[dimen=middle](1,1)\end{pspicture}}
\newcommand\Tiling[1]{%
 \begin{pspicture}#1
     \psframe[fillstyle=boxfill]#1
\end{pspicture}}

  \newcommand\ProtoTile{%
    \Square
    \pscustom{%
      \moveto(-0.9,0.75) % In PSTricks units
      \code{%
        /Times-Italic findfont 8 scalefont setfont
        fill@Dict begin
        (\string\() show row 3 string cvs show (,) show 
        column 3 string cvs show (\string\)) show}
      \moveto(-0.5,0.25) % In PSTricks units
      \code{%
        /Times-Bold findfont 18 scalefont setfont
        1 0 0 setrgbcolor % Red color
        /center { dup stringwidth pop 2 div neg 0 rmoveto } def
        row 1 sub x2 mul column add 3 string cvs center 
        show
        end
      }}}

  \psboxfill{\ProtoTile}
  \Tiling{(12,12)}

  \Tiling{(6,4)}

\end{document}
```

**Comment by zauguin** [comment] 2021-09-29 12:43
(Hopefully) fixed in https://github.com/zauguin/luapstricks/commit/9cbb62787111990d35d737fa891679cec3807a12: Since `moveto` is invoked before running `Box`, I had assumed that the `Box` should be placed at `currentpoint`. Instead it appears that `currentpoint` should be ignored and the box should instead be placed at the currentpoint from the time the box was constructed.

**Comment by hvoss49** [comment] 2021-09-29 13:45
looks fine now with 

```
\def\psboxfill@i{\null\setbox\pst@fillbox\box\pst@hbox\ignorespaces}
```

**Comment by zauguin** [comment] 2021-09-29 13:58
> \def\psboxfill@i{\null\setbox\pst@fillbox\box\pst@hbox\ignorespaces}

See [the answer to your comment in the commit](https://github.com/zauguin/luapstricks/commit/9cbb62787111990d35d737fa891679cec3807a12#commitcomment-57241646): This doesn't really solve the issue and just hides it since it changes the vertical layout a bit. E.g. adding
```
\vspace{17.2bp}
```
before `\Tiling{(6,4)}` would bring the issue back.

**Comment by hvoss49** [comment] 2021-09-29 14:05
Oh, that's not good ...

**Closed as completed** 2021-10-01 11:03 UTC
