### ISSUE TITLE
Compile time can be improved for `\psMatrixPlot`?

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#43] opened 2021-09-02 17:25 UTC
The following file compiles without errors, but is extremely slow in the process:

```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY -dPDFSETTINGS=/prepress -dNOSAFER] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage[dvipsnames]{xcolor}
\usepackage{pstricks-add}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\begin{document}
\begin{center}
\psscalebox{0.6}{%
\begin{pspicture}(-0.5,-0.75)(11,11)
  \psaxes{->}(11,11)
  \psMatrixPlot[dotsize=1.1cm,dotstyle=square*,linecolor=magenta]%
    {10}{10}{data/matrix.data}
  \psMatrixPlot[dotsize=.5cm,dotstyle=o,ChangeOrder]{10}{10}{data/matrix.data}
\end{pspicture}}\quad
\psscalebox{0.6}{%
\begin{pspicture}(-0.5,-0.75)(11,11)
  \psaxes[ticksize=-5pt 0]{->}(11,11)
  \psMatrixPlot[dotsize=1.1cm,dotstyle=square*,linecolor=magenta,XYoffset=-0.5]%
    {10}{10}{data/matrix.data}
  \psMatrixPlot[dotsize=.5cm,dotstyle=o,ChangeOrder,XYoffset=-0.5]{10}{10}{data/matrix.data}
\end{pspicture}}
\end{center}

\begin{pspicture}(-0.5,-0.75)(11,11)
  \psaxes[ticksize=-5pt 0]{->}(11,11)
  \psMatrixPlot[dotscale=3,dotstyle=*,linecolor=blue]{10}{8}{data/matrix.data}
\end{pspicture}

\begin{pspicture}(10,10)
  \psMatrixPlot[colorType=1,xStep=0.05,yStep=0.05]{200}{200}{data/dotmatrix.data}
\end{pspicture}

\begin{pspicture}(10,10)
  \psMatrixPlot[colorType=2,xStep=0.05,yStep=0.05]{200}{200}{data/dotmatrix.data}
\end{pspicture}

\begin{pspicture}(10,10)
  \psMatrixPlot[colorType=3,xStep=0.05,yStep=0.05]{200}{200}{data/dotmatrix.data}
\end{pspicture}

\begin{pspicture}(10,10)
  \psMatrixPlot[colorType=4,xStep=0.05,yStep=0.05]{200}{200}{data/dotmatrix.data}
\end{pspicture}


\begin{center}
\psscalebox{0.7}{%
\begin{pspicture}(-0.5,-0.75)(11,11)
\psaxes[ticksize=-5pt 0]{->}(11,11)
\psMatrixPlot[
  colorType=5,
  colorTypeDef={
    dup /value exch def % save value and leave one on the stack
    value Min sub dMaxMin div neg 1 add 300 mul 400 add \pswavelengthToGRAY
    value 0 eq \pslbrace 1 \psrbrace if %
    value 1 eq \pslbrace 0 \psrbrace if
    setgray
  },
  dotsize=1.1cm,xStep=1,yStep=1,dotstyle=square*]{10}{10}{data/matrix1.data}
\end{pspicture}}
\end{center}

\begin{center}
\psscalebox{0.7}{%
\begin{pspicture}(-0.5,-0.75)(11,11)
\psaxes[ticksize=-5pt 0]{->}(11,11)
\psMatrixPlot[
  colorType=5,dotsize=1.1cm,xStep=1,yStep=1,dotstyle=square*]{10}{10}{data/matrix2.data}
\end{pspicture}}
\end{center}

\end{document}
```

Can anything be done about this from `luapstricks`?

Full MWE [psMatrix.zip](https://github.com/zauguin/luapstricks/files/7100678/psMatrix.zip)

**Comment by zauguin** [comment] 2021-09-03 19:54
The primary issue here is about the use of Type 3 fonts. Currently Type 3 fonts are always expanded and therefore the glyphs have to be drawn over and over again for every point where they are used. This should beg much faster if a Type 3 font solution based on actual Type 3 fonts get's used instead, but that's only planned in the longer term. For now we'll probably have to live with this situation.

**Comment by hvoss49** [comment] 2021-09-03 19:57
We can create a Type 1 version of the PSTricksFontDot. Shoud not be too difficult ...

**Comment by hvoss49** [comment] 2021-09-07 16:51
I defined a new optional argument `PixelPlot` which does not use the dot font, bu ta simple pixel, which will speed up the runtime for a large dotmatrix! Only a few seconds instead of minutes ...

**Comment by pablgonz** [comment] 2021-09-07 17:03
> I defined a new optional argument `PixelPlot` which does not use the dot font, bu ta simple pixel, which will speed up the runtime for a large dotmatrix! Only a few seconds instead of minutes .

That's great :) 

> We can create a Type 1 version of the PSTricksFontDot. Shoud not be too difficult ...

The idea of a `type 1 / otf` font for dots is also great. It would put an end to the problems of editing images in current versions of Adobe products (Illustrartor for example) which no longer support `type 1` :(

**Comment by zauguin** [comment] 2021-09-21 14:41
I created a OpenType version, but it didn't improve the compile time as much as I hoped (about 2 times faster, but still slow).
I pushed the file though, so you can experiment with it by installing it as a system font and creating an empty file named `pst-dots.pro` to stop using the Type 3 version.

**Comment by pablgonz** [comment] 2021-09-21 16:39
It works :D and together with the new `PixelPlot` option it reduces a lot of compile time.

**Comment by pablgonz** [comment] 2021-09-22 17:54
The font also works with https://github.com/zauguin/luapstricks/issues/12#issue-981837866 :D

**Comment by hvoss49** [comment] 2021-09-24 11:24
> I created a OpenType version, but it didn't improve the compile time as much as I hoped (about 2 times faster, but still slow).
> I pushed the file though, so you can experiment with it by installing it as a system font and creating an empty file named `pst-dots.pro` to stop using the Type 3 version.

I want to get rid of the softfont definitions in pst-dots.pro for latex, too. I created a TYpe1 version with otftotfm from your otf version. I get the three files (pfb|tfm|enc) but the question is how to modify the code  so that PSTricks uses the Type1 font instead of the internal softfont?

**Comment by zauguin** [comment] 2021-09-24 15:16
The problem is AFAICT that dvips will not embed the font if it isn't used, so I think the easiest way would be to include it as a PS header which defines the font. See https://github.com/zauguin/luapstricks/compare/type1dots

**Comment by hvoss49** [comment] 2021-09-24 15:46
Thanks, that is the current solution except  that we now load Type 1.  

I will use it and replace it with the contents of pst-dots.pro.  I will try to reencode the font on PS level, then I do not need a pro file, hopefully.

**Comment by zauguin** [comment] 2021-09-24 16:07
>  I will try to reencode the font on PS level then I do not need a pro file, hopefully.

Not sure what you mean with this, but the `.pro` file does not do any reencoding. (It specifies a custom encoding, but that should be allowed in any file format for Type 1 fonts. The `pro` file is just a renamed `t1` file (except for some comments which looked weird in the generated PS file since they duplicated automatically inserted ones) which is only named `pro` since handling it as a PS header seemed simpler than adjusting the PS search paths. Which format would be better?

**Comment by hvoss49** [comment] 2021-09-24 17:15
I uploaded a new version of PSTricks which has your Type1 version as pst-dots.pro.  I will delete all files in the git which are now already uploaded to CTAN.

**Comment by pablgonz** [comment] 2021-09-25 18:20
@hvoss49 @zauguin Can try this?

```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{pstricks}
\pagestyle{empty}
\begin{document}
% SolidOctogon (pst-news08)
\begin{pspicture}[showgrid](3,3)
\psdot[dotstyle=Octogon](1,1)
\psdot[dotstyle=BoldOctogon](2,2)
\psdot[dotstyle=SolidOctogon](3,3)
\end{pspicture}
\end{document}
```

```raw
PSTricks error.  See User's Guide for further information.
                 Type  H <return>  for immediate help.
! Dot style `SolidOctogon' not defined.
\@pstrickserr ... immediate help.}\errmessage {#1}
                                                  \endgroup 
l.15 \psdot[dotstyle=SolidOctogon](3,3)
                                     
? 
```

**Comment by hvoss49** [comment] 2021-09-25 18:50
I added it to `pstricks-dots.tex`

**Comment by zauguin** [comment] 2021-09-25 19:31
> I uploaded a new version of PSTricks which has your Type1 version as pst-dots.pro. I will delete all files in the git which are now already uploaded to CTAN.

It doesn't make a big difference, but I noticed that you used the older version of `pst-dots.pro` (before https://github.com/zauguin/luapstricks/commit/1258b954a2a3cc9f6578ca9a7f49242995b522a9). Functionally it doesn't make a difference, but the change both makes the file more standard and could be slightly faster. (At first I thought these commands where necessary and therefore added them manually since I didn't see where the font gets defined, but then I discovered that this was already being done in the encrypted section)

**Comment by hvoss49** [comment] 2021-09-25 20:17
I See, fixed in my version

**Closed as completed** 2024-05-30 18:38 UTC
